name: Test Action
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build Action"]
    branches: [main]
    types:
      - completed

jobs:
  testaction:  
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: wechuli/actionsrunnersysinfo@main
      - run: sleep 2m
      - run: ls $RUNNER_TEMP
