name: Test Action
on:
  push:
    branches:
      - main
  workflow_dispatch:
 
jobs:
  testaction:
    runs-on: ubuntu-latest
    steps:
      - uses: wechuli/actionsrunnersysinfo@main
      - run: ls $RUNNER_TEMP
