name: Test Action
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build Action"]
    branches: [main]
    types:
      - completed

jobs:
  testaction:  
    runs-on: ubuntu-latest
    steps:
      - uses: wechuli/actionsrunnersysinfo@main
      - run: sleep 5m
      - run: ls $RUNNER_TEMP
