name: Test Action
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build Action"]
    branches: [main]
    types:
      - completed

jobs:
  testaction:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: wechuli/actionsrunnersysinfo@main
      - run: sleep 2m
        if: ${{ matrix.os == 'ubuntu-latest' || matrix.os == 'windows-latest' }}
      - run: sleep 120
        if: ${{ matrix.os == 'macos-latest' }}
      - run: ls $RUNNER_TEMP
  testbuildfailure:
    runs-on: ubuntu-latest
    steps:
      - uses: wechuli/actionsrunnersysinfo@main
      - run: sleep 2m
      - run: exit 1
  testcanceledbuild:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: wechuli/actionsrunnersysinfo@main
      - run: sleep 3m
